---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: petclinic
spec:
  selector:
    matchLabels:
      app: pets
  replicas: 1
  template:
    metadata:
      labels:
        app: pets
    spec:
      containers:
      - name: petclinic-container
        image: azooaksdemo.azurecr.io/petclinic:$(Build.BuildId)
        imagePullPolicy: Always
        ports:
        - containerPort: 8020
      imagePullSecrets:
      - name: petsecret
---
apiVersion: v1
kind: Service
metadata:
  name: petservice
  labels:
    app: pets
spec:
  type: LoadBalancer
  ports:
  - port: 8020
    protocol: TCP
    targetPort: 8085
  selector:
    app: pets
